ci: remove flake check to fix dev store path issue
The 'nix flake check --no-build' command was failing with:
  error: path '/nix/store/...-dev' is not valid

This happens when flake-compat tries to access dev outputs that
aren't realized. Since we already evaluate all nixosConfigurations
and darwinConfigurations separately, we can skip the flake check.

Also added shebang to bin_shim.sh to fix shellcheck error.